# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e962757c75aebdbc118b0a6e7a679f431a83d76d9de3dcf2524521b4f0760540be8f126368b68efb0a037609b842ccea1fe3be0b461fd614b3589b4f2f2a782

test:
  secret_key_base: 6e61a7e27638716ec3924b1b22fa67d733a60deb0e2363bbef2fa20a0d53b076aae247470d85c4fae73a8b0f2564234d11313a77d0637cc58e78ce91a0809685

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
